"""
Dinosaur Facts API.

Routes:
  GET /api/dino/random   -> random dinosaur fact
  GET /api/dino/count    -> total number of facts
  GET /api/dino/<id>     -> fact by zero-based index
"""

import random

FACTS = [
    {
        "name": "Tyrannosaurus Rex",
        "latin": "Tyrannosaurus rex",
        "period": "Late Cretaceous (68–66 MYA)",
        "height": "~13 ft (4 m) at hip",
        "diet": "CARNIVORE",
        "fact": "T. rex had the most powerful bite force of any land animal ever measured — roughly 8,000 lbs of pressure — enough to crush bone. It likely consumed 40,000+ lbs of meat per year.",
    },
    {
        "name": "Triceratops",
        "latin": "Triceratops horridus",
        "period": "Late Cretaceous (68–66 MYA)",
        "height": "~10 ft (3 m) at shoulder",
        "diet": "HERBIVORE",
        "fact": "The frill of Triceratops was likely used for temperature regulation and visual display, not just defense. Its three-horned skull could measure up to 8 ft long — the largest of any land animal.",
    },
    {
        "name": "Velociraptor",
        "latin": "Velociraptor mongoliensis",
        "period": "Late Cretaceous (75–71 MYA)",
        "height": "~1.6 ft (0.5 m) at hip",
        "diet": "CARNIVORE",
        "fact": "The real Velociraptor was turkey-sized and covered in feathers. The iconic sickle claw was likely used to pin prey — like a hawk's talon — rather than slash it.",
    },
    {
        "name": "Brachiosaurus",
        "latin": "Brachiosaurus altithorax",
        "period": "Late Jurassic (154–153 MYA)",
        "height": "~40 ft (12 m) tall",
        "diet": "HERBIVORE",
        "fact": "Brachiosaurus had nostrils on top of its head and front legs longer than its hind legs — unusual for sauropods. It may have eaten the equivalent of a small car's weight in vegetation each week.",
    },
    {
        "name": "Stegosaurus",
        "latin": "Stegosaurus stenops",
        "period": "Late Jurassic (155–150 MYA)",
        "height": "~9 ft (2.7 m) tall",
        "diet": "HERBIVORE",
        "fact": "The plates along Stegosaurus's back were laced with blood vessels, suggesting they acted as solar panels or radiators for thermoregulation. Its brain was roughly the size of a walnut.",
    },
    {
        "name": "Allosaurus",
        "latin": "Allosaurus fragilis",
        "period": "Late Jurassic (155–145 MYA)",
        "height": "~16 ft (4.9 m) tall",
        "diet": "CARNIVORE",
        "fact": "Allosaurus may have hunted like a hatchet, driving its upper jaw down into prey rather than biting like a crocodile. Shed teeth found near sauropod bones suggest it fed on massive herbivores.",
    },
    {
        "name": "Ankylosaurus",
        "latin": "Ankylosaurus magniventris",
        "period": "Late Cretaceous (68–66 MYA)",
        "height": "~5.6 ft (1.7 m) tall",
        "diet": "HERBIVORE",
        "fact": "Ankylosaurus's tail club could swing with enough force to shatter bone. The armor covering its back — called osteoderms — was embedded directly into the skin, not attached to the skeleton.",
    },
    {
        "name": "Diplodocus",
        "latin": "Diplodocus carnegii",
        "period": "Late Jurassic (154–152 MYA)",
        "height": "~16 ft (4.9 m) tall",
        "diet": "HERBIVORE",
        "fact": "Diplodocus could crack its tail like a bullwhip, producing a sonic boom. At up to 90 ft long, over half of that length was just neck and tail.",
    },
    {
        "name": "Spinosaurus",
        "latin": "Spinosaurus aegyptiacus",
        "period": "Mid Cretaceous (99–93.5 MYA)",
        "height": "~23 ft (7 m) tall",
        "diet": "CARNIVORE",
        "fact": "Spinosaurus is the largest carnivorous dinosaur known, longer than T. rex. Recent fossils suggest it was semi-aquatic with dense bones for buoyancy control and a paddle-like tail for swimming.",
    },
    {
        "name": "Parasaurolophus",
        "latin": "Parasaurolophus walkeri",
        "period": "Late Cretaceous (76.5–73 MYA)",
        "height": "~16 ft (4.9 m) tall",
        "diet": "HERBIVORE",
        "fact": "The hollow crest of Parasaurolophus functioned like a trombone — CT scans show a looping internal passage that would have produced a deep, resonant call for communication across long distances.",
    },
    {
        "name": "Pachycephalosaurus",
        "latin": "Pachycephalosaurus wyomingensis",
        "period": "Late Cretaceous (70–66 MYA)",
        "height": "~8 ft (2.4 m) tall",
        "diet": "OMNIVORE",
        "fact": "The dome of Pachycephalosaurus was up to 10 inches (25 cm) thick and had shock-absorbing structures inside. Whether it head-butted rivals or flanked them is still actively debated by paleontologists.",
    },
    {
        "name": "Iguanodon",
        "latin": "Iguanodon bernissartensis",
        "period": "Early Cretaceous (126–122 MYA)",
        "height": "~13 ft (4 m) tall",
        "diet": "HERBIVORE",
        "fact": "Iguanodon had a spiked thumb that was initially misidentified as a nose horn when first discovered. It could walk on two or four legs and had mitten-like hands that could grasp vegetation.",
    },
    {
        "name": "Gallimimus",
        "latin": "Gallimimus bullatus",
        "period": "Late Cretaceous (70–68 MYA)",
        "height": "~6 ft (1.9 m) tall",
        "diet": "OMNIVORE",
        "fact": "Gallimimus was one of the fastest dinosaurs, estimated at 30–40 mph. Its toothless beak and comb-like filter structures suggest it may have scooped up small aquatic creatures like a modern duck.",
    },
    {
        "name": "Carnotaurus",
        "latin": "Carnotaurus sastrei",
        "period": "Late Cretaceous (72–69.9 MYA)",
        "height": "~10 ft (3 m) tall",
        "diet": "CARNIVORE",
        "fact": "Carnotaurus had two bull-like horns above its eyes and the most reduced arms of any large theropod — even smaller relative to body size than T. rex. Skin impressions show a pebbly, non-scaly texture.",
    },
    {
        "name": "Baryonyx",
        "latin": "Baryonyx walkeri",
        "period": "Early Cretaceous (130–125 MYA)",
        "height": "~8 ft (2.5 m) tall",
        "diet": "CARNIVORE",
        "fact": "Baryonyx was discovered with fish scales still preserved in its stomach cavity. Its 12-inch (30 cm) thumb claw was likely used to hook fish from rivers, like a modern grizzly bear.",
    },
    {
        "name": "Protoceratops",
        "latin": "Protoceratops andrewsi",
        "period": "Late Cretaceous (75–71 MYA)",
        "height": "~2.3 ft (0.7 m) tall",
        "diet": "HERBIVORE",
        "fact": "A famous fossil shows Protoceratops locked in combat with a Velociraptor, both buried alive by a collapsing sand dune. It is one of the most dramatic behavior-preserving fossils ever found.",
    },
    {
        "name": "Compsognathus",
        "latin": "Compsognathus longipes",
        "period": "Late Jurassic (150 MYA)",
        "height": "~1 ft (0.3 m) tall",
        "diet": "CARNIVORE",
        "fact": "Compsognathus was one of the smallest known dinosaurs, roughly the size of a chicken. One specimen was found with a complete lizard skeleton inside it — direct evidence of its last meal.",
    },
    {
        "name": "Edmontosaurus",
        "latin": "Edmontosaurus regalis",
        "period": "Late Cretaceous (73–66 MYA)",
        "height": "~13 ft (4 m) tall",
        "diet": "HERBIVORE",
        "fact": "Mummified Edmontosaurus specimens preserved soft tissue revealing a fleshy cock's comb on its head. One mummy showed signs of a healed T. rex bite — it survived an attack.",
    },
    {
        "name": "Maiasaura",
        "latin": "Maiasaura peeblesorum",
        "period": "Late Cretaceous (76.7–75.1 MYA)",
        "height": "~8 ft (2.4 m) tall",
        "diet": "HERBIVORE",
        "fact": "Maiasaura ('good mother lizard') was the first dinosaur proven to care for its young. Nesting colonies with thousands of adults and juveniles were found in Montana, suggesting complex herd behavior.",
    },
    {
        "name": "Oviraptor",
        "latin": "Oviraptor philoceratops",
        "period": "Late Cretaceous (75–71 MYA)",
        "height": "~5 ft (1.5 m) tall",
        "diet": "OMNIVORE",
        "fact": "Oviraptor ('egg thief') was wrongly accused for 70 years. The eggs it was found guarding turned out to be its own — it was brooding them. Its toothless, parrot-like beak could crack shellfish or seeds.",
    },
    {
        "name": "Therizinosaurus",
        "latin": "Therizinosaurus cheloniformis",
        "period": "Late Cretaceous (70 MYA)",
        "height": "~16 ft (5 m) tall",
        "diet": "HERBIVORE",
        "fact": "Therizinosaurus had the longest claws of any known animal — up to 3.3 ft (1 m) each. Despite being related to carnivorous theropods, it evolved to eat plants and had a pot-bellied fermentation gut.",
    },
    {
        "name": "Argentinosaurus",
        "latin": "Argentinosaurus huinculensis",
        "period": "Late Cretaceous (96–94 MYA)",
        "height": "~70 ft (21 m) tall",
        "diet": "HERBIVORE",
        "fact": "Argentinosaurus may be the heaviest land animal ever, estimated at 70–80 tons. A single vertebra stands taller than a human. Its bones had internal honeycomb structures to reduce weight while maintaining strength.",
    },
    {
        "name": "Deinonychus",
        "latin": "Deinonychus antirrhopus",
        "period": "Early Cretaceous (115–108 MYA)",
        "height": "~3.4 ft (1 m) tall",
        "diet": "CARNIVORE",
        "fact": "Deinonychus ('terrible claw') revolutionized dinosaur science in 1969. Its discovery overturned the 'slow, sluggish reptile' view and sparked the now-confirmed theory that birds are living dinosaurs.",
    },
    {
        "name": "Giganotosaurus",
        "latin": "Giganotosaurus carolinii",
        "period": "Late Cretaceous (99.6–97 MYA)",
        "height": "~18 ft (5.5 m) tall",
        "diet": "CARNIVORE",
        "fact": "Giganotosaurus rivaled T. rex in size but had a narrower skull and serrated, blade-like teeth suited for slashing rather than crushing bone. It likely preyed on giant titanosaur sauropods.",
    },
    {
        "name": "Carcharodontosaurus",
        "latin": "Carcharodontosaurus saharicus",
        "period": "Mid Cretaceous (99–94 MYA)",
        "height": "~18 ft (5.5 m) tall",
        "diet": "CARNIVORE",
        "fact": "Named after the great white shark, Carcharodontosaurus had serrated teeth up to 8 inches long. It lived alongside Spinosaurus in North Africa, making that ecosystem arguably the most dangerous ever on land.",
    },
    {
        "name": "Yutyrannus",
        "latin": "Yutyrannus huali",
        "period": "Early Cretaceous (125 MYA)",
        "height": "~10 ft (3 m) tall",
        "diet": "CARNIVORE",
        "fact": "Yutyrannus is the largest known feathered dinosaur, with filament-like proto-feathers up to 8 inches long covering most of its body. Its discovery strongly suggests T. rex also had feathers, at least when young.",
    },
    {
        "name": "Amargasaurus",
        "latin": "Amargasaurus cazaui",
        "period": "Early Cretaceous (130–125 MYA)",
        "height": "~13 ft (4 m) tall",
        "diet": "HERBIVORE",
        "fact": "Amargasaurus had two parallel rows of tall neural spines running down its neck and back. These may have supported a sail for display or thermoregulation, making it one of the most visually distinctive sauropods ever.",
    },
    {
        "name": "Ceratosaurus",
        "latin": "Ceratosaurus nasicornis",
        "period": "Late Jurassic (153–148 MYA)",
        "height": "~13 ft (4 m) tall",
        "diet": "CARNIVORE",
        "fact": "Ceratosaurus had a prominent horn on its nose and bony ridges over each eye. Unlike most theropods, it had small osteoderms running along its back — bony armor embedded in the skin, unusual for a predator.",
    },
    {
        "name": "Dilophosaurus",
        "latin": "Dilophosaurus wetherilli",
        "period": "Early Jurassic (193 MYA)",
        "height": "~9 ft (2.7 m) tall",
        "diet": "CARNIVORE",
        "fact": "Dilophosaurus had two distinctive parallel crests on its skull — purely for display, as they were too thin to withstand combat stress. There is no fossil evidence it spat venom or had a neck frill.",
    },
    {
        "name": "Corythosaurus",
        "latin": "Corythosaurus casuarius",
        "period": "Late Cretaceous (77–75.7 MYA)",
        "height": "~14 ft (4.3 m) tall",
        "diet": "HERBIVORE",
        "fact": "Corythosaurus had a helmet-shaped hollow crest that varied by age and sex, suggesting it played a role in species recognition. Its crest acted as a resonating chamber, producing booming low-frequency calls.",
    },
    {
        "name": "Utahraptor",
        "latin": "Utahraptor ostrommaysorum",
        "period": "Early Cretaceous (126–125 MYA)",
        "height": "~6 ft (1.8 m) tall",
        "diet": "CARNIVORE",
        "fact": "Utahraptor is the largest known dromaeosaurid, with a sickle claw over 9 inches long. A remarkable fossil block contains multiple Utahraptors and their prey all trapped together in a quicksand-like mud.",
    },
    {
        "name": "Microraptor",
        "latin": "Microraptor gui",
        "period": "Early Cretaceous (125–120 MYA)",
        "height": "~1 ft (0.3 m) tall",
        "diet": "CARNIVORE",
        "fact": "Microraptor had four wings — feathers on both arms and legs. Chemical analysis of its fossil feathers suggests it had iridescent black plumage, similar to a modern crow.",
    },
    {
        "name": "Psittacosaurus",
        "latin": "Psittacosaurus mongoliensis",
        "period": "Early Cretaceous (126–101 MYA)",
        "height": "~1.6 ft (0.5 m) tall",
        "diet": "HERBIVORE",
        "fact": "Psittacosaurus is the most species-rich dinosaur genus, with over 10 recognized species. One fossil shows quill-like bristles on its tail, and another reveals countershading coloration for camouflage.",
    },
    {
        "name": "Styracosaurus",
        "latin": "Styracosaurus albertensis",
        "period": "Late Cretaceous (75.5–74.5 MYA)",
        "height": "~6 ft (1.8 m) tall",
        "diet": "HERBIVORE",
        "fact": "Styracosaurus had six long spikes radiating from its frill plus a large nose horn. The elaborate frill was likely brightly colored for attracting mates, making it one of the most visually striking ceratopsians.",
    },
    {
        "name": "Herrerasaurus",
        "latin": "Herrerasaurus ischigualastensis",
        "period": "Late Triassic (231.4 MYA)",
        "height": "~4 ft (1.2 m) tall",
        "diet": "CARNIVORE",
        "fact": "Herrerasaurus is among the earliest true dinosaurs, living just 15 million years after the group's origin. Its mix of primitive and advanced features makes it critical for understanding how dinosaurs first evolved.",
    },
    {
        "name": "Plateosaurus",
        "latin": "Plateosaurus engelhardti",
        "period": "Late Triassic (214–204 MYA)",
        "height": "~13 ft (4 m) tall",
        "diet": "HERBIVORE",
        "fact": "Plateosaurus is one of the most-studied early dinosaurs, with over 100 individuals found across Europe. It could NOT walk on its knuckles — a long-held misconception debunked by detailed skeletal analysis.",
    },
    {
        "name": "Lambeosaurus",
        "latin": "Lambeosaurus lambei",
        "period": "Late Cretaceous (76.5–75.1 MYA)",
        "height": "~16 ft (4.9 m) tall",
        "diet": "HERBIVORE",
        "fact": "Lambeosaurus had a hatchet-shaped hollow crest that changed dramatically with age — nearly absent in juveniles but massively developed in adults, similar to how a rooster's comb develops.",
    },
    {
        "name": "Mamenchisaurus",
        "latin": "Mamenchisaurus sinocanadorum",
        "period": "Late Jurassic (160–145 MYA)",
        "height": "~29 ft (9 m) tall",
        "diet": "HERBIVORE",
        "fact": "Mamenchisaurus had the longest neck of any known dinosaur — up to 50 ft (15 m) — comprising over half its total body length. Its neck had 19 vertebrae, more than any other sauropod.",
    },
    {
        "name": "Nigersaurus",
        "latin": "Nigersaurus taqueti",
        "period": "Mid Cretaceous (115–105 MYA)",
        "height": "~5.6 ft (1.7 m) tall",
        "diet": "HERBIVORE",
        "fact": "Nigersaurus had over 500 teeth arranged in more than 50 columns, replaced constantly like a conveyor belt. Its wide, vacuum-cleaner-like muzzle was adapted for cropping ground-level plants with extraordinary efficiency.",
    },
    {
        "name": "Ornithomimus",
        "latin": "Ornithomimus edmontonicus",
        "period": "Late Cretaceous (76–66 MYA)",
        "height": "~5 ft (1.5 m) tall",
        "diet": "OMNIVORE",
        "fact": "Ornithomimus ('bird mimic') looked remarkably like a modern ostrich and may have reached 44 mph. Specimens from Alberta preserve wing-like arm feathers, suggesting display behavior similar to modern ratites.",
    },
    {
        "name": "Suchomimus",
        "latin": "Suchomimus tenerensis",
        "period": "Early Cretaceous (112 MYA)",
        "height": "~13 ft (4 m) tall",
        "diet": "CARNIVORE",
        "fact": "Suchomimus ('crocodile mimic') had a long, narrow snout with over 100 conical teeth perfect for catching fish. It was closely related to Spinosaurus and shared the same North African waterways.",
    },
    {
        "name": "Supersaurus",
        "latin": "Supersaurus vivianae",
        "period": "Late Jurassic (153–145 MYA)",
        "height": "~34 ft (10.5 m) tall",
        "diet": "HERBIVORE",
        "fact": "Supersaurus may be the longest dinosaur ever, reaching up to 108 ft (33 m). Its single shoulder blade stands taller than most humans. Despite its immense size, it likely reached full adult size in under 40 years.",
    },
    {
        "name": "Kentrosaurus",
        "latin": "Kentrosaurus aethiopicus",
        "period": "Late Jurassic (155–150 MYA)",
        "height": "~5.5 ft (1.7 m) tall",
        "diet": "HERBIVORE",
        "fact": "Kentrosaurus replaced the back plates seen in Stegosaurus with paired spikes along its hindquarters. Computer models show its tail could swing at 50 mph — enough to drive a spike through bone.",
    },
    {
        "name": "Ouranosaurus",
        "latin": "Ouranosaurus nigeriensis",
        "period": "Early Cretaceous (112 MYA)",
        "height": "~9 ft (2.7 m) tall",
        "diet": "HERBIVORE",
        "fact": "Ouranosaurus had tall neural spines along its back forming a sail or hump. Living in hot Cretaceous Africa alongside Spinosaurus, its sail may have regulated body temperature or stored energy reserves as fat.",
    },
    {
        "name": "Saltasaurus",
        "latin": "Saltasaurus loricatus",
        "period": "Late Cretaceous (70–65.5 MYA)",
        "height": "~12 ft (3.7 m) tall",
        "diet": "HERBIVORE",
        "fact": "Saltasaurus was the first sauropod discovered with body armor — small bony plates embedded in its skin. Once thought impossible for an animal of that size, its discovery forced a major rethink of sauropod biology.",
    },
    {
        "name": "Sinoceratops",
        "latin": "Sinoceratops zhuchengensis",
        "period": "Late Cretaceous (73–66 MYA)",
        "height": "~8 ft (2.4 m) tall",
        "diet": "HERBIVORE",
        "fact": "Sinoceratops is the only large ceratopsian found in Asia, suggesting it was an evolutionary bridge between Asian protoceratopsians and the giant North American ceratopsians like Triceratops.",
    },
    {
        "name": "Torosaurus",
        "latin": "Torosaurus latus",
        "period": "Late Cretaceous (68–66 MYA)",
        "height": "~8 ft (2.4 m) tall",
        "diet": "HERBIVORE",
        "fact": "Torosaurus had the largest skull of any known land animal, stretching up to 9 ft including its massive frill. Some scientists controversially argue it is simply an old Triceratops with a remodeled skull.",
    },
    {
        "name": "Dracorex",
        "latin": "Dracorex hogwartsia",
        "period": "Late Cretaceous (66 MYA)",
        "height": "~4 ft (1.2 m) tall",
        "diet": "HERBIVORE",
        "fact": "Dracorex hogwartsia — 'dragon king of Hogwarts' — was named by children who donated the fossil to a museum. Most paleontologists now believe it is simply a juvenile Pachycephalosaurus whose dome had not yet grown.",
    },
    {
        "name": "Kosmoceratops",
        "latin": "Kosmoceratops richardsoni",
        "period": "Late Cretaceous (76.5–75.5 MYA)",
        "height": "~6.6 ft (2 m) tall",
        "diet": "HERBIVORE",
        "fact": "Kosmoceratops holds the record for the most facial horns of any animal ever — 15 in total, including horns over the eyes, cheeks, and a row curving forward along the frill like ornamental hooks.",
    },
    {
        "name": "Nothronychus",
        "latin": "Nothronychus mckinleyi",
        "period": "Late Cretaceous (91 MYA)",
        "height": "~13 ft (4 m) tall",
        "diet": "HERBIVORE",
        "fact": "Nothronychus was a North American therizinosaur — a pot-bellied, plant-eating theropod. Its discovery demonstrated that herbivory evolved multiple times independently within the meat-eating theropod lineage.",
    },
    {
        "name": "Minmi",
        "latin": "Minmi paravertebra",
        "period": "Early Cretaceous (119–113 MYA)",
        "height": "~3 ft (0.9 m) tall",
        "diet": "HERBIVORE",
        "fact": "Minmi is the most completely known ankylosaur from the Southern Hemisphere. It had extra bony plates called paravertebrae running along muscles beside its spine — unique among all known dinosaurs.",
    },
    {
        "name": "Zuniceratops",
        "latin": "Zuniceratops christopheri",
        "period": "Late Cretaceous (90 MYA)",
        "height": "~3.6 ft (1.1 m) tall",
        "diet": "HERBIVORE",
        "fact": "Zuniceratops was discovered by an 8-year-old on a family fossil hunt. It is the oldest ceratopsian known from North America with true brow horns, linking Asian and American evolutionary lineages.",
    },
    {
        "name": "Pachyrhinosaurus",
        "latin": "Pachyrhinosaurus canadensis",
        "period": "Late Cretaceous (73.5–72.5 MYA)",
        "height": "~8 ft (2.4 m) tall",
        "diet": "HERBIVORE",
        "fact": "Pachyrhinosaurus had no nose horn — instead it bore a massive flat boss of bone on its snout like a battering ram. Bone beds in Alberta suggest it migrated in herds of thousands, similar to modern caribou.",
    },
    {
        "name": "Tsintaosaurus",
        "latin": "Tsintaosaurus spinorhinus",
        "period": "Late Cretaceous (83.5–70.6 MYA)",
        "height": "~13 ft (4 m) tall",
        "diet": "HERBIVORE",
        "fact": "Tsintaosaurus had a unicorn-like spike projecting forward from its skull. Paleontologists long debated whether it was real; CT scans confirmed it was a hollow nasal crest used for sound production.",
    },
    {
        "name": "Yi Qi",
        "latin": "Yi qi",
        "period": "Mid Jurassic (163 MYA)",
        "height": "~0.5 ft (0.15 m) tall",
        "diet": "CARNIVORE",
        "fact": "Yi qi ('strange wing') had bat-like membrane wings supported by a unique wrist bone not seen in any other dinosaur. It represents a completely independent and ultimately dead-end experiment in powered flight.",
    },
    {
        "name": "Yangchuanosaurus",
        "latin": "Yangchuanosaurus shangyouensis",
        "period": "Late Jurassic (163–145 MYA)",
        "height": "~13 ft (4 m) tall",
        "diet": "CARNIVORE",
        "fact": "Yangchuanosaurus was the apex predator of Jurassic China. It was so similar to Allosaurus that some researchers suspect the two share a common ancestor via an ancient land bridge connecting Asia and North America.",
    },
    {
        "name": "Shunosaurus",
        "latin": "Shunosaurus lii",
        "period": "Mid Jurassic (170–165 MYA)",
        "height": "~16 ft (4.9 m) tall",
        "diet": "HERBIVORE",
        "fact": "Shunosaurus is unusual among sauropods for having a bony club at the tip of its tail, convergently evolving the same defensive weapon as ankylosaurs. It is also one of the most completely known Jurassic sauropods.",
    },
    {
        "name": "Tarchia",
        "latin": "Tarchia gigantea",
        "period": "Late Cretaceous (75–68 MYA)",
        "height": "~5 ft (1.5 m) tall",
        "diet": "HERBIVORE",
        "fact": "Tarchia is the largest and most recent ankylosaurid from Asia. Its skull was so thoroughly armored that even its eyelids had bony shields. Its tail club alone could weigh over 100 lbs.",
    },
    {
        "name": "Mamenchisaurus",
        "latin": "Mamenchisaurus hochuanensis",
        "period": "Late Jurassic (160–145 MYA)",
        "height": "~26 ft (8 m) tall",
        "diet": "HERBIVORE",
        "fact": "Mamenchisaurus had the longest neck of any known dinosaur relative to body size. Some estimates place its neck at over 30 ft — longer than most school buses.",
    },
    {
        "name": "Wannanosaurus",
        "latin": "Wannanosaurus yansiensis",
        "period": "Late Cretaceous (80 MYA)",
        "height": "~2 ft (0.6 m) tall",
        "diet": "HERBIVORE",
        "fact": "Wannanosaurus is the smallest known pachycephalosaur, about the size of a rabbit. Its flat skull suggests head-butting behavior may have evolved later in the group, with early members using domes only for display.",
    },
    {
        "name": "Wuerhosaurus",
        "latin": "Wuerhosaurus homheni",
        "period": "Early Cretaceous (130–120 MYA)",
        "height": "~8 ft (2.4 m) tall",
        "diet": "HERBIVORE",
        "fact": "Wuerhosaurus is one of the last known stegosaurids, persisting into the Cretaceous long after most relatives died out. Its plates were lower and more rounded than Stegosaurus, suggesting different thermoregulation.",
    },
    {
        "name": "Muttaburrasaurus",
        "latin": "Muttaburrasaurus langdoni",
        "period": "Early Cretaceous (100 MYA)",
        "height": "~9 ft (2.7 m) tall",
        "diet": "HERBIVORE",
        "fact": "Muttaburrasaurus had an inflated, hollow nasal dome that likely amplified its calls. It is the most complete dinosaur fossil found in Australia and has become a symbol of Australian paleontology.",
    },
    {
        "name": "Polacanthus",
        "latin": "Polacanthus foxii",
        "period": "Early Cretaceous (132–112 MYA)",
        "height": "~4.6 ft (1.4 m) tall",
        "diet": "HERBIVORE",
        "fact": "Polacanthus had a sacral shield — a solid sheet of fused armor covering its hip region — unlike any other ankylosaur. It was one of the earliest-known ankylosaurs and the first large armored dinosaur found in England.",
    },
    {
        "name": "Hypsilophodon",
        "latin": "Hypsilophodon foxii",
        "period": "Early Cretaceous (130–125 MYA)",
        "height": "~3 ft (0.9 m) tall",
        "diet": "HERBIVORE",
        "fact": "Hypsilophodon was incorrectly thought for 70 years to live in trees like a squirrel. Later analysis showed it was a speedy ground-dweller with self-sharpening cheek teeth that worked like a multi-blade grinder.",
    },
    {
        "name": "Nodosaurus",
        "latin": "Nodosaurus textilis",
        "period": "Late Cretaceous (98–93.5 MYA)",
        "height": "~5 ft (1.5 m) tall",
        "diet": "HERBIVORE",
        "fact": "Nodosaurus lacked the tail club of its ankylosaur cousins, relying purely on passive armor. A related nodosaur found in Alberta is the best-preserved armored dinosaur ever found — soft tissue and color patterns intact.",
    },
    {
        "name": "Masiakasaurus",
        "latin": "Masiakasaurus knopfleri",
        "period": "Late Cretaceous (70–66 MYA)",
        "height": "~2 ft (0.6 m) tall",
        "diet": "CARNIVORE",
        "fact": "Masiakasaurus was named after Dire Straits guitarist Mark Knopfler because the field team was playing his music when they found the fossil. Its front teeth projected forward for snatching fish or insects.",
    },
    {
        "name": "Scelidosaurus",
        "latin": "Scelidosaurus harrisonii",
        "period": "Early Jurassic (196 MYA)",
        "height": "~4 ft (1.2 m) tall",
        "diet": "HERBIVORE",
        "fact": "Scelidosaurus is one of the earliest armored dinosaurs and may be ancestral to both stegosaurs and ankylosaurs. Complete specimens found in Dorset preserve fine details of skin texture.",
    },
    {
        "name": "Rugops",
        "latin": "Rugops primus",
        "period": "Late Cretaceous (95 MYA)",
        "height": "~8 ft (2.4 m) tall",
        "diet": "CARNIVORE",
        "fact": "Rugops ('wrinkle face') had a heavily pitted skull with rows of holes suggesting scales, osteoderms, or a fleshy head display. Its weak jaw structure implies it may have been primarily a scavenger.",
    },
    {
        "name": "Vulcanodon",
        "latin": "Vulcanodon karibaensis",
        "period": "Early Jurassic (201–189 MYA)",
        "height": "~11 ft (3.4 m) tall",
        "diet": "HERBIVORE",
        "fact": "Vulcanodon is one of the earliest true sauropods, bridging prosauropods and the giant long-necked giants that followed. It was found in Zimbabwe surrounded by volcanic rock, giving it its fiery name.",
    },
    {
        "name": "Segnosaurus",
        "latin": "Segnosaurus galbinensis",
        "period": "Late Cretaceous (93.9–83.6 MYA)",
        "height": "~10 ft (3 m) tall",
        "diet": "HERBIVORE",
        "fact": "Segnosaurus was so bizarre when discovered that paleontologists could not agree what it was — early theories suggested it was a turtle or an aberrant prosauropod. It was eventually classified as a therizinosaur.",
    },
    {
        "name": "Archaeopteryx",
        "latin": "Archaeopteryx lithographica",
        "period": "Late Jurassic (150 MYA)",
        "height": "~1 ft (0.3 m) tall",
        "diet": "CARNIVORE",
        "fact": "Archaeopteryx is the iconic transitional fossil between dinosaurs and birds, with feathered wings but also teeth, clawed wing fingers, and a bony tail. High-resolution scans show asymmetric flight feathers — it could fly.",
    },
    {
        "name": "Gorgosaurus",
        "latin": "Gorgosaurus libratus",
        "period": "Late Cretaceous (76.6–75.1 MYA)",
        "height": "~11 ft (3.4 m) tall",
        "diet": "CARNIVORE",
        "fact": "Gorgosaurus was a smaller, earlier cousin of T. rex that relied more on speed. A juvenile fossil was found with two young Citipati dinosaurs in its stomach — evidence that young tyrannosaurs targeted different prey than adults.",
    },
    {
        "name": "Daspletosaurus",
        "latin": "Daspletosaurus torosus",
        "period": "Late Cretaceous (77–74 MYA)",
        "height": "~10 ft (3 m) tall",
        "diet": "CARNIVORE",
        "fact": "Daspletosaurus ('frightful lizard') had bite marks on its skull from another Daspletosaurus, suggesting intraspecific combat or cannibalism. It may be a direct evolutionary ancestor of T. rex.",
    },
    {
        "name": "Edmontonia",
        "latin": "Edmontonia rugosidens",
        "period": "Late Cretaceous (76.5–66 MYA)",
        "height": "~5 ft (1.5 m) tall",
        "diet": "HERBIVORE",
        "fact": "Edmontonia had massive shoulder spikes that could be used to shove rivals — likely in combat over territory or mates. Unlike ankylosaurs, it lacked a tail club but more than compensated with its front-end weaponry.",
    },
    {
        "name": "Camptosaurus",
        "latin": "Camptosaurus dispar",
        "period": "Late Jurassic (155–145 MYA)",
        "height": "~6.5 ft (2 m) tall",
        "diet": "HERBIVORE",
        "fact": "Camptosaurus ('flexible lizard') was one of the first dinosaurs described from North America. It is considered ancestral to the hadrosaur lineage, representing a key evolutionary step toward the duck-billed dinosaurs.",
    },
    {
        "name": "Hadrosaurus",
        "latin": "Hadrosaurus foulkii",
        "period": "Late Cretaceous (80–78 MYA)",
        "height": "~13 ft (4 m) tall",
        "diet": "HERBIVORE",
        "fact": "Hadrosaurus was the first nearly complete dinosaur skeleton ever found in North America (1858) and the first mounted for public display. Its discovery transformed how scientists understood dinosaur posture and diversity.",
    },
    {
        "name": "Alioramus",
        "latin": "Alioramus remotus",
        "period": "Late Cretaceous (70 MYA)",
        "height": "~6 ft (1.8 m) tall",
        "diet": "CARNIVORE",
        "fact": "Alioramus was a slender, long-snouted tyrannosaur from Mongolia with a row of small bumps on its nose. Some scientists think it represents a juvenile growth stage rather than a distinct species — the debate continues.",
    },
    {
        "name": "Sinraptor",
        "latin": "Sinraptor dongi",
        "period": "Late Jurassic (161–155 MYA)",
        "height": "~10 ft (3 m) tall",
        "diet": "CARNIVORE",
        "fact": "Sinraptor ('Chinese thief') is one of the best-known large theropods from Jurassic China. Its skull showed healed bite marks from another Sinraptor, demonstrating that large predators fought each other 160 million years ago.",
    },
    {
        "name": "Lurdusaurus",
        "latin": "Lurdusaurus arenatus",
        "period": "Early Cretaceous (125–112 MYA)",
        "height": "~10 ft (3 m) tall",
        "diet": "HERBIVORE",
        "fact": "Lurdusaurus was a massively built iguanodontian with short, thick limbs and a barrel-shaped body — more like a hippo than a typical dinosaur. It likely wallowed in river shallows to support its enormous weight.",
    },
    {
        "name": "Omeisaurus",
        "latin": "Omeisaurus tianfuensis",
        "period": "Mid-Late Jurassic (160 MYA)",
        "height": "~26 ft (8 m) tall",
        "diet": "HERBIVORE",
        "fact": "Omeisaurus had an extremely long neck comprising nearly a third of its total 50 ft length. It is one of the most abundant Jurassic sauropods found in China, with multiple complete skeletons known.",
    },
    {
        "name": "Sinornithosaurus",
        "latin": "Sinornithosaurus millenii",
        "period": "Early Cretaceous (122 MYA)",
        "height": "~1 ft (0.3 m) tall",
        "diet": "CARNIVORE",
        "fact": "Sinornithosaurus is one of the best-preserved feathered dinosaurs. Some researchers controversially proposed it had a venomous bite based on grooved teeth and a possible venom gland, though this remains debated.",
    },
    {
        "name": "Abelisaurus",
        "latin": "Abelisaurus comahuiensis",
        "period": "Late Cretaceous (83–80 MYA)",
        "height": "~13 ft (4 m) tall",
        "diet": "CARNIVORE",
        "fact": "Abelisaurus gave its name to an entire family of Southern Hemisphere predators. It had a deep, narrow skull full of large fenestrae — weight-reducing skull openings that allowed a more powerful bite for its mass.",
    },
    {
        "name": "Supersaurus",
        "latin": "Supersaurus lourinhanensis",
        "period": "Late Jurassic (150 MYA)",
        "height": "~34 ft (10.5 m) tall",
        "diet": "HERBIVORE",
        "fact": "European Supersaurus specimens push the length of this genus to over 100 ft. Its vertebrae were so large that the original discovery team initially assumed they had found multiple animals, not just one.",
    },
]

# Deduplicate by latin name to ensure data integrity
_seen: set[str] = set()
_unique = []
for f in FACTS:
    if f["latin"] not in _seen:
        _seen.add(f["latin"])
        _unique.append(f)
FACTS = _unique


def handle(path_parts: list[str]) -> tuple[int, dict, dict]:
    """
    Handle /api/dino/<path_parts>.

      /api/dino/random      -> random fact
      /api/dino/count       -> total count
      /api/dino/<int>       -> fact by index
    """
    route = path_parts[0] if path_parts else "random"

    if route == "count":
        return 200, {"count": len(FACTS)}, {}

    if route == "random" or not path_parts:
        fact = random.choice(FACTS)
        return 200, {**fact, "total": len(FACTS)}, {}

    try:
        idx = int(route)
    except ValueError:
        return 400, {"error": f"Unknown route: '{route}'"}, {}

    if not (0 <= idx < len(FACTS)):
        return 404, {"error": f"Index {idx} out of range (0–{len(FACTS) - 1})"}, {}

    return 200, {**FACTS[idx], "index": idx, "total": len(FACTS)}, {}
